remote_theme: pages-themes/leap-day@v0.2.0
title: Space of PE
description: This is my portfolio. Here you will find all of my programming projects.
defaults:
  -
    values:
      author: "Pavlin Edrev/PE/Scrollerer"

plugins:
- jekyll-remote-theme
