remote_theme: pages-themes/leap-day@v0.2.0
title: Space of PE
og:title: Portfolio
description: Welcome to my programming portfolio. Here you will find most of my programming projects.
defaults:
  -
    values:
      author: "Pavlin Edrev/PE/Scrollerer"

plugins:
- jekyll-remote-theme
